spring:
  datasource:
    url: jdbc:mysql://${{ MYSQLUSER }}:${{ MYSQLPASSWORD }}@${{ MYSQLHOST }}:${{ MYSQLPORT }}/${{ MYSQLDATABASE }}
  username: ${MYSQLUSER}
  password: ${MYSQLPASSWORD}
  name: project1

